name: Build A101 SOS APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Kodları Çek
      - name: Checkout
        uses: actions/checkout@v2

      # Docker ile Otomatik Buildozer Kurulumu ve Derleme
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      # APK Dosyasını Yükleme (Artifact olarak)
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: marketbank-apk
          path: bin/*.apk
