name: Build A101 SOS APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Java 17 Kurulumu (Android SDK için gerekli)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gerekli Kütüphaneler ve Buildozer
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git python3 python3-dev
          sudo apt-get install -y ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libtool automake autoconf libffi-dev
          pip3 install buildozer cython==0.29.33

      # Buildozer ile APK Derleme
      - name: Build with Buildozer
        run: |
          yes | buildozer android debug

      # APK Dosyasını Yükleme (Artifact olarak)
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: marketbank-apk
          path: bin/*.apk
